-- Create web jobs table for the web API
-- Note: id is UUID v7 generated by the Go application (time-ordered UUIDs).
-- Postgres has no built-in v7 generator, so no DEFAULT is set — all INSERTs must supply an id.
CREATE TABLE IF NOT EXISTS jobs (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    data JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source TEXT NOT NULL DEFAULT 'web' CHECK (source IN ('web', 'api')),
    result_count INTEGER NOT NULL DEFAULT 0
);

-- Create index for status queries
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status, created_at);

-- Grant permissions to scraper user
GRANT ALL PRIVILEGES ON TABLE jobs TO scraper;