# Default values for leads-scraper-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas for the leads scraper deployment
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  # -- Container image repository
  repository: feelguuds/leads-scraper-service
  # -- Image pull policy
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# -- Override the chart name
nameOverride: ""
# -- Override the full name
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {} # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # -- Service type (ClusterIP, NodePort, LoadBalancer)
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8080

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  # -- Enable ingress controller resource
  enabled: false
  # -- IngressClass that will be be used
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  # -- Enable autoscaling
  enabled: true
  # -- Minimum number of replicas
  minReplicas: 1
  # -- Maximum number of replicas
  maxReplicas: 5
  # -- Target CPU utilization percentage
  targetCPUUtilizationPercentage: 95
  # -- Target memory utilization percentage
  targetMemoryUtilizationPercentage: 95
  # Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

# Test configuration
tests:
  # -- Enable helm tests
  enabled: false
  healthCheck:
    # -- Enable health check test
    enabled: true
    # -- Health check endpoint path
    path: "/health"
  configCheck:
    # -- Enable config check test
    enabled: true

# Application specific configuration
config:
  # -- Enable Redis task handler
  redis:
    enabled: true
    # -- Redis connection string
    dsn: ""
    # -- Redis workers
    workers: 10
  # Database Configuration (Required)
  database:
    # -- Database connection string (Required)
    # @default -- ""
    # Format: postgres://username:password@host:port/dbname
    dsn: ""

  # AWS Configuration (Optional)
  aws:
    # -- AWS access key
    accessKey: ""
    # -- AWS secret key
    secretKey: ""
    # -- AWS region
    region: "us-east-1"
    lambda:
      # -- Enable AWS Lambda integration
      enabled: false
      # -- Lambda chunk size
      chunkSize: 100
      # -- Enable Lambda invoker
      invoker: false
      # -- Lambda function name
      functionName: ""
    s3:
      # -- S3 bucket name
      bucket: "leads-scraper-service"

  # Scraper Configuration
  scraper:
    # -- Enable web server mode
    webServer: true
    # Core settings
    concurrency: 11
    depth: 5
    language: "en"
    searchRadius: 10000
    zoomLevel: 15
    # Optional features
    emailExtraction: false
    fastMode: true
    exitOnInactivity: ""
    proxies: ""

# PostgreSQL subchart configuration
postgresql:
  # -- Enable PostgreSQL dependency
  enabled: true
  auth:
    # -- PostgreSQL username
    username: postgres
    # -- PostgreSQL password
    password: postgres
    # -- PostgreSQL database name
    database: leads_scraper
    # -- Existing secret for PostgreSQL password
    existingSecret: ""
  primary:
    persistence:
      # -- Enable PostgreSQL persistence
      enabled: true
      # -- PostgreSQL PVC size
      size: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    service:
      ports:
        # -- PostgreSQL service port
        postgresql: 5432
    # PostgreSQL configuration
    extraEnvVars:
      - name: POSTGRESQL_MAX_CONNECTIONS
        value: "100"
      - name: POSTGRESQL_SHARED_BUFFERS
        value: "128MB"
